### ISSUE TITLE
Endpoint.Load

### ISSUE THREAD

**Issue by Will-Lo** [TeamCtrlC/cruise-control#19]
#4

**Comment by jeffreyfei** [comment]
`/load:
  get:
    summary: Get the cluster load once Cruise Control is in RUNNING state
    parameters:
      - name: start
        in: query
        description: The start time of the cluster load in milliseconds since Epoch
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: end
        in: query
        description: The end time of the cluster load in miliseconds since Epoch
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: time
        in: query
        description: The end time of the cluster load in miliseconds since Epoch (Mutually exclusive to end)
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: allow_capacity_estimation
        in: query
        description: Whether allow broker capacity to be estimated from other broker in the cluster
        schema:
          type: boolean
          default: true
      - name: populate_disk_info
        in: query
        description: Whether show the load of each disk of broker
        schema:
          type: boolean
          default: false
      - name: json
        in: query
        description: If true, cruise-control's response is in JSON format
        schema:
          type: boolean
          default: false
      - name: verbose
        in: query
        description: Return detailed state information
        schema: 
          type: boolean
          default: false`

**Comment by jeffreyfei** [comment]
/load:
  get:
    summary: Get the cluster load once Cruise Control is in RUNNING state
    parameters:
      - name: start
        in: query
        description: The start time of the cluster load in milliseconds since Epoch
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: end
        in: query
        description: The end time of the cluster load in miliseconds since Epoch
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: time
        in: query
        description: The end time of the cluster load in miliseconds since Epoch (Mutually exclusive to end)
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: allow_capacity_estimation
        in: query
        description: Whether allow broker capacity to be estimated from other broker in the cluster
        schema:
          type: boolean
          default: true
      - name: populate_disk_info
        in: query
        description: Whether show the load of each disk of broker
        schema:
          type: boolean
          default: false
      - name: json
        in: query
        description: If true, cruise-control's response is in JSON format
        schema:
          type: boolean
          default: false
      - name: verbose
        in: query
        description: Return detailed state information
        schema: 
          type: boolean
          default: false

**Comment by jeffreyfei** [comment]
Please copy pasta I was bored
```
/load:
  get:
    summary: Get the cluster load once Cruise Control is in RUNNING state
    parameters:
      - name: start
        in: query
        description: The start time of the cluster load in milliseconds since Epoch
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: end
        in: query
        description: The end time of the cluster load in miliseconds since Epoch
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: time
        in: query
        description: The end time of the cluster load in miliseconds since Epoch (Mutually exclusive to end)
        schema:
          type: integer
          format: int64
          minimum: 0
      - name: allow_capacity_estimation
        in: query
        description: Whether allow broker capacity to be estimated from other broker in the cluster
        schema:
          type: boolean
          default: true
      - name: populate_disk_info
        in: query
        description: Whether show the load of each disk of broker
        schema:
          type: boolean
          default: false
      - name: json
        in: query
        description: If true, cruise-control's response is in JSON format
        schema:
          type: boolean
          default: false
      - name: verbose
        in: query
        description: Return detailed state information
        schema: 
          type: boolean
          default: false
```
